package org.cyk.utility.time;

public interface TimeConstant {

	Short NUMBER_OF_MILLISECOND_PER_SECOND = 1000;
	Integer NUMBER_OF_MILLISECOND_PER_MINUTE = NUMBER_OF_MILLISECOND_PER_SECOND * 60;
	Integer NUMBER_OF_MILLISECOND_PER_HOUR = NUMBER_OF_MILLISECOND_PER_MINUTE * 60;
	
	Byte NUMBER_OF_SECOND_PER_MINUTE = 60;
	Byte NUMBER_OF_MINUTE_PER_HOUR = 60;
	
	String UNIT_MILLISECOND = "MILLISECOND";
	String UNIT_SECOND = "SECOND";
	String UNIT_MINUTE = "MINUTE";
	String UNIT_HOUR = "HOUR";
	String UNIT_DAY = "DAY";
}
