package org.cyk.utility.instant;

import org.cyk.utility.character.CharacterConstant;

public interface InstantConstant {
	
	String HOUR_MINUTE_PATTERN_FORMAT = "%s:%s";
	String HOUR_MINUTE_SECOND_PATTERN_FORMAT = HOUR_MINUTE_PATTERN_FORMAT+":%s";
	String HOUR_MINUTE_SECOND_MILLISECOND_PATTERN_FORMAT = HOUR_MINUTE_SECOND_PATTERN_FORMAT+":%s";
	String DAY_MONTH_YEAR_PATTERN_FORMAT = "%s/%s/%s";
	String DATE_TIME_PATTERN_FORMAT = "%s"+CharacterConstant.SPACE+"%s";
	
	String DAY_MONTH_YEAR_PATTERN = String.format(DAY_MONTH_YEAR_PATTERN_FORMAT, "dd","MM","yyyy");
	String HOUR_MINUTE_PATTERN = String.format(HOUR_MINUTE_PATTERN_FORMAT, "HH","mm");
	String HOUR_MINUTE_SECOND_PATTERN = String.format(HOUR_MINUTE_SECOND_PATTERN_FORMAT, "HH","mm","ss");
	String HOUR_MINUTE_SECOND_MILLISECOND_PATTERN = String.format(HOUR_MINUTE_SECOND_MILLISECOND_PATTERN_FORMAT, "HH","mm","ss","SSS");
	String DAY_MONTH_YEAR_HOUR_MINUTE_PATTERN = String.format(DATE_TIME_PATTERN_FORMAT, DAY_MONTH_YEAR_PATTERN,HOUR_MINUTE_PATTERN);
	String DAY_MONTH_YEAR_HOUR_MINUTE_SECOND_PATTERN = String.format(DATE_TIME_PATTERN_FORMAT, DAY_MONTH_YEAR_PATTERN,HOUR_MINUTE_SECOND_PATTERN);
	String DAY_MONTH_YEAR_HOUR_MINUTE_SECOND_MILLISECOND_PATTERN = String.format(DATE_TIME_PATTERN_FORMAT, DAY_MONTH_YEAR_PATTERN,HOUR_MINUTE_SECOND_MILLISECOND_PATTERN);
	
}
